method: bayes
name: tweets_classification_sweep
program: main.py
metric:
  goal: maximize
  name: eval/f1
parameters:
  training.per_device_train_batch_size:
    values:
      - 64
      - 128
      - 256
  training.learning_rate:
    min: 1.e-5
    max: 1.e-4
